apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
     template: '{{.DOCKER_REGISTRY}}/root/shopizer-ecomm:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/root/shopizer-ecomm:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: shopizer-ecomm
        chartPath: charts/shopizer-ecomm
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/root/shopizer-ecomm'
          image.tag: '{{.DIGEST_HEX}}'
